# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrzGQKSISwGdHCVDULgxqDHogPyx0qCl
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

cancer.keys()

df = pd.DataFrame(cancer['data'],columns = cancer['feature_names'])

df.head()

from sklearn.model_selection import train_test_split

x=df
y = cancer['target']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=101)

from sklearn.svm import SVC

model = SVC()

model.fit(x_train,y_train)

prediction = model.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,prediction))
print('\n')
print(classification_report(y_test,prediction))

from sklearn.model_selection import GridSearchCV

param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

grid = GridSearchCV(SVC(),param_grid,verbose = 3)

grid.fit(x_train,y_train)

grid.best_params_

grid.best_estimator_

grid_prediction = grid.predict(x_test)

print(classification_report(y_test,grid_prediction))
print('\n')
print(confusion_matrix(y_test,grid_prediction))

